language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - PROFILE=non-existant
    - PROFILE=spring41
    - PROFILE=spring41-next
    - PROFILE=spring42-next
cache:
  directories:
    - $HOME/.m2
sudo: false
install: true
script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ]; then mvn clean deploy -Pdistribute --settings mySettings.xml;
  else mvn clean dependency:list test -P${PROFILE} -Dsort; fi